routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index');

Auth::routes();
Route::group(['middleware' => 'web_auth','prefix' => 'admin','as'=>'admin.'], function () {
//DEPARTMENT
Route::get('', 'HomeController@index')->name('home');
Route::get('departments','Admin\DepartmentController@index')->name('departments.index');
Route::get('departments/store','Admin\DepartmentController@store')->name('departments.store');

//COMPANY
Route::get('companies','Admin\CompanyController@index')->name('companies.index');
Route::get('companies/store','Admin\CompanyController@store')->name('companies.store');
//when company id is passed it gives all the departments belongs to that company.
Route::get('company/departments','Admin\CompanyController@companyDepartments')->name('company.departments');

//EMPLOYEE
Route::get('employees','Admin\EmployeeController@index')->name('employees.index');
Route::get('employees/store','Admin\EmployeeController@store')->name('employees.store');
});

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Employee;

class Department extends Model
{
    //
    protected $fillable=['department_name'];

    public function companies()
    {
        return $this->belongsToMany('App\Company','company_departments','department_id','company_id');
    }
    public function employees()
    {
        return $this->belongsToMany('App\Employee','employee_departments','department_id','employee_id');
    }
}

app/Http/Controllers/Admin/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\DepartmentRequest;
use App\Department;

class DepartmentController extends Controller
{
    //
    private $base_path="admin.departments";
    private $base_route="admin.departments";

    public function index(){
        $departments=Department::all();
        return view($this->base_path.'.index',compact('departments'));
    }

    public function store(DepartmentRequest $request){
        Department::create($request->all());
        return redirect()->route($this->base_route.'.index')->with('success','Department is added Successfully');
    }
}

app/Http/Controllers/Api/DepartmentController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\Department as DepartmentResource;
use App\Http\Services\DataExistance;
use Illuminate\Http\Request;
use App\Traits\ApiResponser;
use App\Company;

class DepartmentController extends Controller
{
    //
    use ApiResponser;

    private $data_existance;

    public function __construct(DataExistance $de){
        //instantiating the DataExistance class, and assiging its object to private variable
        $this->data_existance=$de;
    }
   
    public function departmentsCompany($company_id){
        $company_exist=$this->data_existance->checkCompanyExist($company_id);
        if($company_exist["status"]==false)
            return $this->errorResponse('404', "Company with this id doesnot exist");

        $company=Company::find($company_id);
        $departments=$company->departments;
        return DepartmentResource::collection($departments);
    }
}

resources/views/admin/departments/partials/create_department_form.blade.php
<form action="{{route('admin.departments.store')}}">
    @csrf
    <div class="form-group">
        <label for="department_name">Deparment Name: <span style="color:red">*</span></label>
        <input type="text" class="form-control" id="department_name" name="department_name" required>
    </div>
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</form>

resources/views/admin/departments/partials/departments_list.blade.php
<table class="table table-bordered">
                <thead>
                <tr>
                    <th>S.N</th>
                    <th>Department</th>
                </tr>
                </thead>
                <tbody>
                @foreach($departments as $key=>$department)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$department->department_name}}</td>
                </tr>
                @endforeach
                
                </tbody>
            </table>