routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index');

Auth::routes();
Route::group(['middleware' => 'web_auth','prefix' => 'admin','as'=>'admin.'], function () {
//DEPARTMENT
Route::get('', 'HomeController@index')->name('home');
Route::get('departments','Admin\DepartmentController@index')->name('departments.index');
Route::get('departments/store','Admin\DepartmentController@store')->name('departments.store');

//COMPANY
Route::get('companies','Admin\CompanyController@index')->name('companies.index');
Route::get('companies/store','Admin\CompanyController@store')->name('companies.store');
//when company id is passed it gives all the departments belongs to that company.
Route::get('company/departments','Admin\CompanyController@companyDepartments')->name('company.departments');

//EMPLOYEE
Route::get('employees','Admin\EmployeeController@index')->name('employees.index');
Route::get('employees/store','Admin\EmployeeController@store')->name('employees.store');
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    //
    protected $table="employees";

    protected $guarded=[];

    public function departments()
    {
        return $this->belongsToMany('App\Department','employee_departments','employee_id','department_id');
    }

    public function company()
    {
        return $this->belongsTo('App\Company','company_id');
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\EmployeeRequest;
use App\Employee;
use App\Company;

class EmployeeController extends Controller
{
    //
    private $base_path="admin.employees";
    private $base_route="admin.employees";

    public function index(){
        $companies=Company::all();
        $employees=Employee::with("company")->with("departments")->get();
        return view($this->base_path.'.index',compact('employees','companies'));
    }

    public function store(EmployeeRequest $request){
        $employee=Employee::create($request->except("departments_id"));
        $employee->departments()->sync($request->input("departments_id"));
        return redirect()->route($this->base_route.'.index')->with("success","employee is added successfully");
    }
}

app/Http/Controllers/Api/EmployeesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\Employees as EmployeesResource;
use App\Http\Resources\Employee as EmployeeResource;
use App\Http\Resources\Department as DepartmentResource;
use App\Http\Services\DataExistance;
use Illuminate\Http\Request;
use App\Traits\ApiResponser;
use App\Department;
use App\Company;
use App\Employee;

class EmployeesController extends Controller
{
    //
    use ApiResponser;

    private $data_existance;

    public function __construct(DataExistance $de){
        //instantiating the DataExistance class, and assiging its object to private variable
        $this->data_existance=$de;
    }
    
    public function employeesCompany($company_id){
        //check if company with this id exist or not
        $company_exist=$this->data_existance->checkCompanyExist($company_id);
        if($company_exist["status"]==false)
            return $this->errorResponse('404', "Company with this id doesnot exist");

        $company=Company::find($company_id);
        //fetching employees belonging to this company using relationship
        $employees=$company->employees;
        //accessing query params 'paginate'
        $paginate=request()->paginate;
        if($paginate>0)
            $employees=$company->employees()->paginate($paginate);

        $employees=$this->filterData($employees);
        return EmployeesResource::collection($employees);
    }

    public function employeesInCompanyDepartment($company_id, $department_id){
        //checking if company with this id exist or not
        $company_exist=$this->data_existance->checkCompanyExist($company_id);
        //checking if department with this id exist or not
        $department_exist=$this->data_existance->checkDepartmentExist($department_id);
        
        if($company_exist['status']==true && $department_exist['status']==true){
            $department=Department::find($department_id);
            $employees=$department->employees;
            $employees=$employees->where("company_id",$company_id);
            $employees=$this->filterData($employees);
            return EmployeesResource::collection($employees);
        }else{
            $message=$company_exist["message"]." ".$department_exist["message"];
            return $this->errorResponse(404,$message);
        }    
    }

    public function Detail($employee_id){
        //checking if employee with this id exist or not
        $employee_exist=$this->data_existance->checkEmployeeExist($employee_id);

        if($employee_exist['status']==false)
            return $this->errorResponse('404', $employee_exist["message"]);

        $employee=Employee::find($employee_id);
        return new EmployeeResource($employee);
    }
}

resources/views/admin/employees/partials/create_employee_form.blade.php
<form action="{{route('admin.employees.store')}}">
    @csrf
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="company_name">Employee Name: @include('layouts.requiredMark')</label>
                <input type="text" class="form-control" id="employee_name" name="name" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="company_contact">Contact Number: @include('layouts.requiredMark')</label>
                <input type="text" class="form-control" id="contact" name="contact" required>
            </div>
        </div>
    </div> 

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="company_contact">Email: @include('layouts.requiredMark')</label>
                <input type="text" class="form-control" id="email" name="email" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="company_contact">Designation: @include('layouts.requiredMark')</label>
                <input type="text" class="form-control" id="designation" name="designation" required>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Assign Employee to company: @include('layouts.requiredMark')</label>
                <select name="company_id"class="form-control" id="company" required>
                <option disabled="disabled" selected="selected">Choose Company</option>
                @foreach($companies as $key=>$company)
                    <option value="{{$company->id}}">{{$company->name}}</option>
                @endforeach
                </select>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <label>Select the departments: @include('layouts.requiredMark')<span style="color:red">(Press ctrl to select multiple departments)</span></label>
                <select name="departments_id[]" class="form-control" id="company_departments" required>
                    <option disabled="disabled" selected="selected">Select Departments</option>
                </select>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</form>

resources/views/admin/employees/partials/employees_list.blade.php
<table class="table table-bordered">
        <thead>
        <tr>
            <th>S.N</th>
            <th>Employee Name</th>
            <th>Email</th>
            <th>Contact Number</th>
            <th>Designation</th>
            <th>Company</th>
            <th>Departments</th>
        </tr>
        </thead>
        <tbody>
        @foreach($employees as $key=>$employee)
        <tr>
            <td>{{$key+1}}</td>
            <td>{{$employee->name}}</td>
            <td>{{$employee->email}}</td>
            <td>{{$employee->contact}}</td>
            <td>{{$employee->designation}}</td>
            <td>{{$employee->company->name}}</td>
            <td>  <button type="button" class="btn btn-secondary btn-sm" >
                {{count($employee->departments)}}
            </button>
            @foreach($employee->departments as $key=>$department)
            <span class="badge badge-success ml-1">{{$department->department_name}}</span>
            @endforeach</td>
        </tr>
        @endforeach
        
        </tbody>
    </table>