routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index');

Auth::routes();
Route::group(['middleware' => 'web_auth','prefix' => 'admin','as'=>'admin.'], function () {
//DEPARTMENT
Route::get('', 'HomeController@index')->name('home');
Route::get('departments','Admin\DepartmentController@index')->name('departments.index');
Route::get('departments/store','Admin\DepartmentController@store')->name('departments.store');

//COMPANY
Route::get('companies','Admin\CompanyController@index')->name('companies.index');
Route::get('companies/store','Admin\CompanyController@store')->name('companies.store');
//when company id is passed it gives all the departments belongs to that company.
Route::get('company/departments','Admin\CompanyController@companyDepartments')->name('company.departments');

//EMPLOYEE
Route::get('employees','Admin\EmployeeController@index')->name('employees.index');
Route::get('employees/store','Admin\EmployeeController@store')->name('employees.store');
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Company extends Model
{
    //

    protected $table="companies";
    public $timestamps = false;
    protected $fillable=[
        "name",
        "location",
        "contact",
    ];


    public function departments()
    {
        return $this->belongsToMany('App\Department','company_departments','company_id','department_id');
    }

    public function employees()
    {
        return $this->hasMany('App\Employee','company_id');
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\CompanyRequest;
use Illuminate\Support\Collection;
use App\Company;
use App\Department;

class CompanyController extends Controller
{
    //
    private $base_path="admin.companies";
    private $base_route="admin.companies";

    public function index(){
        $companies=Company::withCount('departments')->with('departments')->get();
        $departments=Department::all();
        return view($this->base_path.'.index',compact('companies','departments'));
    }
    public function store(CompanyRequest $request){
        $company=Company::create($request->all());
        $company->departments()->sync($request->input('company_departments'));
        return redirect()->route($this->base_route.'.index')->with('success','Company is added Successfully');
    }

    public function companyDepartments(Request $request){
        $company_departments=Company::find($request->input('company_id'))->departments;
        return $company_departments;
    }
}

app/Http/Controllers/Api/CompanyController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\Company as CompanyResource;
use App\Http\Resources\CompanyCollection;
use App\Http\Resources\Department as DepartmentResource;
use Illuminate\Http\Request;
use App\Traits\ApiResponser;
use App\Company;

class CompanyController extends Controller
{
    //
    use ApiResponser;
    
    public function index(){
        $companies=Company::all();
        $paginate=request()->paginate;

        if($paginate>0)
            $companies=Company::paginate($paginate);

        $companies=$this->filterData($companies);
        return new CompanyCollection($companies);
        // return CompanyResource::collection($companies);
    }


   
}

resources/views/admin/companies/partials/companies_list.blade.php
<table class="table table-bordered">
        <thead>
        <tr>
            <th>S.N</th>
            <th>Company Name</th>
            <th>Company Location</th>
            <th>Contact Number</th>
            <th>no of Department</th>
        </tr>
        </thead>
        <tbody>
        @foreach($companies as $key=>$company)
        <tr>
            <td>{{$key+1}}</td>
            <td>{{$company->name}}</td>
            <td>{{$company->location}}</td>
            <td>{{$company->contact}}</td>
            <td>
                <button type="button" class="btn btn-secondary btn-sm" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
                {{$company->departments_count}}
            </button>
            @foreach($company->departments as $key=>$department)
            <span class="badge badge-success ml-1">{{$department->department_name}}</span>
            @endforeach
            </td>
        </tr>
        @endforeach
        
        </tbody>
    </table>

resources/views/admin/companies/partials/create_company_form.blade.php
<form action="{{route('admin.companies.store')}}">
    @csrf
    <div class="form-group">
        <label for="company_name">Company Name: @include('layouts.requiredMark')</label>
        <input type="text" class="form-control" id="company_name" name="name" required>
    </div>
    <div class="form-group">
        <label for="company_location">Company Location: @include('layouts.requiredMark')</label>
        <input type="text" class="form-control" id="location" name="location" required>
    </div>

    <div class="form-group">
        <label for="company_contact">Contact Number: @include('layouts.requiredMark')</label>
        <input type="text" class="form-control" id="location" name="contact" required>
    </div>
    <div class="form-group">
        <label>Select Departments For Company <span style="color:red">@include('layouts.requiredMark') (Press ctrl to select multiple departments)</span></label>
    <select multiple name="company_departments[]"class="form-control" id="exampleFormControlSelect2">
      <option disabled="disabled">Choose Department</option>
      @foreach($departments as $key=>$department)
        <option value="{{$department->id}}">{{$department->department_name}}</option>
      @endforeach
    </select>
</div>
    
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</form>